name: SpectralOps Audit
on: [push]
env:
  SPECTRAL_DSN:    ${{ secrets.SPECTRAL_DSN }}
  MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
jobs:
  build:
    name: Spectral
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Spectral Install
        run: curl -L "https://get.spectralops.io/latest/x/sh?dsn=$SPECTRAL_DSN" | sh
      - name: Spectral Scan
        run: $HOME/.spectral/spectral github -c $PWD/config/.spectral -k org -t $MY_GITHUB_TOKEN cncf
