name: SpectralOps Scan Succeed
on: [push]
env:
  SPECTRAL_DSN: ${{ secrets.SPECTRAL_DSN }}
jobs:
  build:
    name: Spectral
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Spectral Install
        run: curl -L "https://get.spectralops.io/latest/x/sh?dsn=$SPECTRAL_DSN" | sh
      - name: Spectral Scan
        # the config file contains ignore all -- so all succeed ¯\_(ツ)_/¯
        run: $HOME/.spectral/spectral scan -c $PWD/config/.spectral
